### ISSUE TITLE
Remove duplicate Name column from side

### ISSUE THREAD

**Issue by skidvd** [angular-gantt/angular-gantt#378] opened 2015-03-03 20:24 UTC
I am using a combination of the gantt-tree and gantt-table directives in my app:

    <div gantt data="data" column-magnet="'1 day'" time-frames-magnet="true" headers="['quarter', 'month', 'week']"
            view-scale="'1 week'" auto-expand="both" expand-to-fit="true" task-out-of-range="expand"
            current-date="currentDateMode" current-date-value="getToday"
            api="ganttApi"> 
        <gantt-tree enabled="true" header="Milestone">
        </gantt-tree>
        <gantt-table enabled="true" columns="['tasks[0].model.enabled', 'tasks[0].model.estimatedDuration']"
                     headers="{'tasks[0].model.enabled': 'Active', 'tasks[0].model.estimatedDuration': 'ED'}"
                     formatters="options.columnsFormatters">
        <gantt-table/>
        <gantt-groups enabled="true" display="display">
        </gantt-groups>
        <gantt-bounds enabled="true"><gantt-bounds/>
        <gantt-movable enabled="true" allow-row-switching="false">
        </gantt-movable>
        <gantt-tooltips enabled="true" date-format="'ddd M/D/YYYY'">
        </gantt-tooltips>
        <gantt-progress enabled="true">
        </gantt-progress>
    </div>

This provides me the expand/collapse behavior I need for grouped tasks via gantt-tree, as well as the ability to display additional columns on the side (columns="['tasks[0].model.enabled', 'tasks[0].model.estimatedDuration']").  However, this results in the Name column appear twice in the side (once as part of the tree on the far left and then once again as the last column of the side despite the fact that is it intentionally omitted from both the columns and headers attributes.  How can I avoid this and only have the tree version of the Name column displayed?

Secondly, is there a way to introduce controls into the side column contents?  For example, I would like to have the added 'tasks[0].model.enabled' column be rendered as a checkbox that I can attach app specific behavior to (ng-change) and be bound back to the appropriate model.  I will appreciate any insights and examples please.

**Comment by Toilal** [comment] 2015-03-06 13:58
@skidvd You can customize with HTML using `columnsContent` property. It's only available in github master, but will be released soon. Docs for master are at [readthedocs](http://angular-gantt.readthedocs.org/en/latest/plugins/table/).

**Comment by Toilal** [comment] 2015-03-06 13:59
For the 1st question/bug, I need more time, sorry.

**Comment by Toilal** [comment] 2015-03-18 13:17
@skidvd Your first issue is caused by a typo.

`<gantt-table/>` instead of `</gantt-table>` cause the plugin to get loaded a second time, with default configuratio.

**Closed by Toilal** 2015-03-18 13:17 UTC
Labels: bug
