### ISSUE TITLE
switching bound data sets on the fly causes lost/stale data

### ISSUE THREAD

**Issue by Mendanbar** [angular-gantt/angular-gantt#412] opened 2015-04-21 16:45 UTC
I've been using the gantt library to display and edit scenarios.  I have the json data stored in an array, where each element represents one gantt (json) data structure.  I then use a select box to switch the index into the array, and in html I set gantt data=array[selectID].  This works, but in cases where the data is similar (specifically, if the scenario is a duplicate, but with a few extra tasks added), the extra tasks will stop appearing  when swapping between the two scenarios. I've even tried first switching to an empty scenario, but the gantt chart still seems to hold some memory of the data that was previously present. The only way to reliably load all of the correct data for a given scenraio is to start fresh (reload the page). below is a sample of json that causes the issue:

**Original JSON**
``` 
[
	{
		"name": "Parent",
		"classes": "",
		"id": "6b2810c4-e9b3-6186-cbdf-aea6a76a1b98",
		"content": "  {{row.model.name}}"
	},
	{
		"name": "Child",
		"parent": "6b2810c4-e9b3-6186-cbdf-aea6a76a1b98",
		"tasks": [
			{
				"name": "Original Task",
				"classes": "",
				"color": "#725579",
				"from": "2015-02-10T18:00:00.000Z",
				"to": "2015-02-10T18:05:00.000Z",
				"progress": 25,
				"id": "19b74a9b-77ad-cedc-2b74-9cc12ce2403c"
			}
		],
		"id": "995fe869-bd4f-31e2-6f31-3ac7ca19bce9",
		"content": " {{row.model.name}}",
		"data": ""
	}
]
```
**Alternate JSON**
```
[
	{
		"name": "Parent",
		"classes": "",
		"id": "6b2810c4-e9b3-6186-cbdf-aea6a76a1b98",
		"content": "  {{row.model.name}}"
	},
	{
		"name": "Child",
		"parent": "6b2810c4-e9b3-6186-cbdf-aea6a76a1b98",
		"tasks": [
			{
				"name": "Original Task",
				"classes": "",
				"color": "#725579",
				"from": "2015-02-10T18:00:00.000Z",
				"to": "2015-02-10T18:05:00.000Z",
				"progress": 25,
				"id": "19b74a9b-77ad-cedc-2b74-9cc12ce2403c"
			},
			{
				"id": "a434dbc4-3364-a96e-ef67-36de8941cf06",
				"name": "Lost Task",
				"classes": "",
				"data": "",
				"color": "#725579",
				"from": "2015-01-01T19:35:00.000Z",
				"to": "2015-01-05T06:35:00.000Z"
			},
			{
				"id": "5fe09dfd-2b16-b2eb-2ed4-485145b02585",
				"name": "Other Lost Task",
				"classes": "",
				"data": "",
				"color": "#725579",
				"from": "2015-01-09T14:35:00.000Z",
				"to": "2015-01-14T07:35:00.000Z"
			}
		],
		"id": "995fe869-bd4f-31e2-6f31-3ac7ca19bce9",
		"content": " {{row.model.name}}",
		"data": ""
	}
]
```

When first switching from original to alternate, "Lost Task" and "Other Lost Task" appear as they should.  But if the data source is swapped back to the array element containing the Original JSON, then back to the Alternate, the lost tasks do **not** reappear.  I've also tried forcing the scope to apply in an attempt to trigger a refresh, but this has no effect.

Here are the library versions I'm using: 
- AngularJS v1.3.8
- angular-gantt v1.2.5
- Chrome browser v42.0.2311.90 m

**Comment by Schweigi** [comment] 2015-04-21 23:54
Hi @Mendanbar, could you prepare a Plunkr to demonstrate this problem? You can use the following Plunkr as starting point: http://plnkr.co/cNqoyX.

This would help us a lot to locate a potential issue.

**Comment by Mendanbar** [comment] 2015-04-22 15:43
@Schweigi here is a fork of the plunkr that you posted:
http://plnkr.co/jitx2Fel9TmpstlQNrXb

You can see the problem by using the select box to swap between "original" and "added stuff".  The "original" data set is simply a subset of "added stuff".  Loading "added stuff" the first time works great, but after switching back to "original", any subsequent select of "added stuff" results in no visual change.

**Comment by Schweigi** [comment] 2015-04-22 17:04
Thx for the Plunkr. I can reproduce it and will take a look at it.

**Comment by Schweigi** [comment] 2015-04-23 02:13
I added an output of the data to the Plunkr: http://embed.plnkr.co/BMQKQ99RonlRc280ju53/preview

As you can see the task data gets deleted when switching back and fort. Why that? When loading the "smaller" data the Gantt assumes you want to delete the previous, now non existing tasks. Since you manage two different objects it will delete it in the previous object. Then next time you load the previous object again, the tasks are gone and can not be loaded again.

This issue can be solved by creating a copy of the data before assigning it to the Gantt.

So instead of:
```
$scope.data = data1;
// data switch
$scope.data = data2;
```

you do:
```
$scope.data = angular.copy(data1);
// data switch
$scope.data = angular.copy(data2);
```

You could also make your own copy function in case the angular.copy function is too slow.

**Closed by Schweigi** 2015-04-23 02:13 UTC
Labels: bug

**Comment by Mendanbar** [comment] 2015-04-23 06:00
@Schweigi Thanks for the explanation!  This sheds some light on a lot of the instability I've been seeing in my app.  I was just fundamentally misunderstanding how angular-gantt handles data behind the scenes.

In case anyone also encounters this issue, I've linked to a plunkr with the full solution below:
http://plnkr.co/wYkrUTkm5y5HKHPeExRx

**Comment by Schweigi** [comment] 2015-04-23 16:46
Glad it works now!
