### ISSUE TITLE
Task out-of-range display bug

### ISSUE THREAD

**Issue by PeterM88** [angular-gantt/angular-gantt#445] opened 2015-07-13 08:39 UTC
Hey there,
i am experiencing an strange bug in my project which integrates the angular-gantt chart. In case that a task starts in a previous week the first day of other tasks in the selected time range is not displayed. I attached a screenshot of the bug in the demo application. You can see that the "day 2"  task should start at monday but the monday is missing. Now when i expand the time range to the previous week it displays the task correctly starting on the 14th(second screenshot). Did anyone now how to fix it?

![angular-gantt-bug2](https://cloud.githubusercontent.com/assets/1671229/8645874/674e599a-294b-11e5-838a-78758380dc04.png)

![angular-gantt-bug](https://cloud.githubusercontent.com/assets/1671229/8645788/b9020d96-294a-11e5-827f-9cdde3158e09.png)

**Comment by dieuhd** [comment] 2015-08-10 04:02
![screen shot 2015-08-10 at 12 59 01 pm](https://cloud.githubusercontent.com/assets/3165692/9159255/ec273d60-3f5f-11e5-9aff-e4cb174b7616.png)

Same problem. 
Does anyone have solution for my problem ?

**Comment by Toilal** [comment] 2015-08-20 12:44
Do you use the latest released version ?

**Comment by dieuhd** [comment] 2015-08-21 03:58
@Toilal : Yes, i am using angular-gantt version 1.2.6.

**Comment by BartRobeyns** [comment] 2015-09-07 13:04
I'm also experiencing this bug. It is caused by the 'autoExpand' option of the getPositionByDate-method.
If you disable autoExpand on all getPositionByDate-calls in Task.prototype.updatePosAndSize (i.e. getPositionByDate(...,**false**)), it works correctly. 
@Toilal: I'm guessing this is option exists to support the expand-to-fit option, but since I don't actually know: can you tell us whether it's safe to do this if expand-to-fit is not enabled?

**Comment by dieuhd** [comment] 2015-09-08 10:23
@BartRobeyns thanks you, it's worked

**Comment by Toilal** [comment] 2015-12-13 13:32
I think this issue is now fixed in master. Please reopen I you still reproduce this one.

**Closed by Toilal** 2015-12-13 13:32 UTC
Labels: 4 - Done, bug
