### ISSUE TITLE
Implementing the columnsContent feature

### ISSUE THREAD

**Issue by andela-atogun** [angular-gantt/angular-gantt#371] opened 2015-02-26 22:04 UTC
Am trying to use the columnContent to load up elements wrapped in html.

Following the steps in the documentation(placing it in the row object) does not seem to work. The HTML is not compiled and is just printed out with the tags into the chart.

**Comment by Toilal** [comment] 2015-02-27 06:59
I can't reproduce, see [branch issue/371 demo](http://rawgit.com/angular-gantt/angular-gantt/issue/371/demo/dist/index.html).

I've created a link on Sprint 1 From column using this feature.

Which angularJS version do you use ?

**Comment by andela-atogun** [comment] 2015-02-27 12:31
Version 1.3.9

**Comment by andela-atogun** [comment] 2015-02-27 15:44
@Toilal An implementation of it on plunkr http://plnkr.co/edit/ySfy1GcR8d4qokcOrlZn?p=preview, still I can not see HTML elements besides the column name.

**Comment by andela-oadenekan** [comment] 2015-03-04 15:32
http://plnkr.co/edit/lUZzbLT1dxqzkQ8UmD5q?p=preview
@Toilal: nice job so far on gantt. But i am also having issues including pictures from my database to the side bar beside the names. Its rather showing the html tag instead of pictures.
I will be awaiting your prompt response.
Thanks

**Comment by andela-oadenekan** [comment] 2015-03-05 15:27
@Toilal : can the gantt-bind-compile-html attribute directive accepts image?

**Comment by andela-oadenekan** [comment] 2015-03-06 12:10
![screen shot 2015-03-06 at 1 04 04 pm](https://cloud.githubusercontent.com/assets/8451337/6525106/975c2266-c401-11e4-9b00-3e1c16aee082.png)
@Toilal : This the view i get when i needed my image to show on the side bar. I attempt using trustAsHtml but got no desired result. Seems your setting only converts and display as string. Is there an option of getting the view to display as html so my people picture can show?

**Comment by Toilal** [comment] 2015-03-06 13:43
@andela-oadenekan You can use HTML content in name. Name is for string only. If you need to customize the HTML content, you need to use `content` and `columnsContent` from table plugin and tree plugin.

If you are using `master`, it's documented in [readthedocs](https://angular-gantt.readthedocs.org/en/latest/) (official angular gantt website docs is for latest release, but it's quite dated for now).

That behing said @andela-atogun has reported an issue and `content` doesn't seem to work properly, but don't really know why at the moment because it works in demo. Don't have time to check this for now, but I don't forget, i'll try to have a look on monday.

**Comment by andela-oadenekan** [comment] 2015-03-06 13:47
@Toilal : Thanks for the response. I will look forward to Monday if it doesn't get sorted out.

**Comment by andela-oadenekan** [comment] 2015-03-10 08:59
@Toilal : Just a check to know if you took a  look at the issue of the content and column content regarding display of picture as content in the row names

**Comment by andela-oadenekan** [comment] 2015-03-12 14:05
@Toilal :+1: 
Any update on the chart image display?
Thanks.

**Comment by ssamsundar** [comment] 2015-03-13 14:09
Here is the default template for labels body
 'plugins/labels/labelsBody.tmpl.html'
```
     <div class="gantt-labels-body" ng-style="getLabelsCss()">
            <div gantt-vertical-scroll-receiver>
                <div ng-repeat="row in gantt.rowsManager.visibleRows track by row.model.id">
                    <div gantt-row-label
                         class="gantt-row-label gantt-row-height"
                         ng-class="row.model.classes"
                         ng-style="{\'height\': row.model.height}">
                        <span class="gantt-label-text">{{row.model.name}}</span>
                    </div>
                </div>
            </div>
        </div>

```

This can be customized to support for images.

```
 <div gantt-row-label
         class="gantt-row-label gantt-row-height"
         ng-class="row.model.classes"
         ng-style="{\'height\': row.model.height}">
      <img src="{{row.model.data.assign.picture}}" />
      <span class="gantt-label-text">{{row.model.name}}</span>
</div>

```

Here, model.data is the custom object, which can be used for holding the other row information including image url

After changing the template, Refer the template in gantt-label tag. Also update the css to expand the height of the row.


Note: I dint try this out myself. There could be some issue as well.

**Comment by Toilal** [comment] 2015-03-14 07:34
@andela-atogun @andela-oadenekan 

Sorry for the delay

@andela-atogun : You forgot to add font awesome CSS to your example. [It works](http://plnkr.co/edit/XYYkD8tf5b2LQs5kL5nx?p=preview).

@andela-oadenekan : Is your issue the same as @andela-atogun ? In case I would assume it is a big *won't fix*, because it just works.

**Closed** 2015-03-18 13:22 UTC
Labels: question, waiting reply, wontfix
